name: linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cxx: [ g++-5, g++-10, clang++-9 ]
        build_type: [ Debug, Release ]
        std: [ 14 ]
        with_tests: [ ON ]

        include:
          - cxx: g++-5
            std: 14
            with_tests: ON
            install: sudo apt install g++-5

            # Builds with valgrind, sanitizers
          - cxx: g++-10
            build_type: Release
            std: 17
            with_tests: ON
            cmake_options: -DQUILL_USE_VALGRIND=ON
            ctest_options: -T memcheck
            install: sudo apt install valgrind
          - cxx: clang++-9
            build_type: Release
            std: 17
            with_tests: ON
            cmake_options: -DQUILL_SANITIZE_ADDRESS=ON
          - cxx: clang++-9
            build_type: Release
            std: 17
            with_tests: ON
            cmake_options: -DQUILL_SANITIZE_THREAD=ON

            # Builds with bounded queue and no exceptions
          - cxx: g++-10
            build_type: Release
            std: 17
            with_tests: OFF
            cmake_options: -DQUILL_USE_BOUNDED_QUEUE=ON
          - cxx: g++-10
            build_type: Release
            std: 17
            with_tests: OFF
            cmake_options: -DQUILL_NO_EXCEPTIONS=ON

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: |
          ${{matrix.install}}
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.cmake_options}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} -DQUILL_BUILD_TESTS=${{matrix.with_tests}} \
                -DQUILL_BUILD_EXAMPLES=ON -DQUILL_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest --build-config ${{matrix.build_type}} ${{matrix.ctest_options}} --verbose --output-on-failure --parallel 2
